version: '3.8'
services:
  minio:
    image: minio/minio:latest
    command: server /data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "4000:4000"
    depends_on:
      - minio
    volumes:
      - ./backend:/usr/src/app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  minio_data:
